name: Firebase CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write Firebase Service Account JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-key.json

      - name: Firebase Deploy
        run: |
          firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} \
                          --only hosting,firestore,functions,storage,database,remoteconfig,extensions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-key.json
